/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LilG_Com_FozruciX_JavaScript_JSClassFilter */

#ifndef _Included_com_LilG_Com_FozruciX_JavaScript_JSClassFilter
#define _Included_com_LilG_Com_FozruciX_JavaScript_JSClassFilter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
