/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LilG_Com_FozruciX */

#ifndef _Included_com_LilG_Com_FozruciX
#define _Included_com_LilG_Com_FozruciX
#ifdef __cplusplus
extern "C" {
#endif
#undef com_LilG_Com_FozruciX_VERSION
#define com_LilG_Com_FozruciX_VERSION 2.2
#undef com_LilG_Com_FozruciX_jokeCommands
#define com_LilG_Com_FozruciX_jokeCommands 0L
#undef com_LilG_Com_FozruciX_prefixRan
#define com_LilG_Com_FozruciX_prefixRan 1L
#undef com_LilG_Com_FozruciX_cleverBotInt
#define com_LilG_Com_FozruciX_cleverBotInt 2L
#undef com_LilG_Com_FozruciX_pandoraBotInt
#define com_LilG_Com_FozruciX_pandoraBotInt 3L
#undef com_LilG_Com_FozruciX_jabberBotInt
#define com_LilG_Com_FozruciX_jabberBotInt 4L
#undef com_LilG_Com_FozruciX_nickInUse
#define com_LilG_Com_FozruciX_nickInUse 5L
#undef com_LilG_Com_FozruciX_color
#define com_LilG_Com_FozruciX_color 6L
#undef com_LilG_Com_FozruciX_respondToPMs
#define com_LilG_Com_FozruciX_respondToPMs 7L
#undef com_LilG_Com_FozruciX_dataLoaded
#define com_LilG_Com_FozruciX_dataLoaded 8L
#undef com_LilG_Com_FozruciX_checkLinks
#define com_LilG_Com_FozruciX_checkLinks 9L
/*
 * Class:     com_LilG_Com_FozruciX
 * Method:    jniTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_LilG_Com_FozruciX_jniTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
