; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23506.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_05COLMCDPH@Hello?$AA@			; `string'
EXTRN	__security_check_cookie:PROC
;	COMDAT ??_C@_05COLMCDPH@Hello?$AA@
CONST	SEGMENT
??_C@_05COLMCDPH@Hello?$AA@ DB 'Hello', 00H		; `string'
CONST	ENDS
PUBLIC	Java_com_LilG_Com_FozruciX_jniTest
PUBLIC	?NewStringUTF@JNIEnv_@@QEAAPEAV_jstring@@PEBD@Z	; JNIEnv_::NewStringUTF
; Function compile flags: /Ogtpy
;	COMDAT ?NewStringUTF@JNIEnv_@@QEAAPEAV_jstring@@PEBD@Z
_TEXT	SEGMENT
this$ = 8
utf$dead$ = 16
?NewStringUTF@JNIEnv_@@QEAAPEAV_jstring@@PEBD@Z PROC	; JNIEnv_::NewStringUTF, COMDAT
; File c:\program files\java\jdk1.8.0_51\include\jni.h
; Line 1611
	mov	rax, QWORD PTR [rcx]
	lea	rdx, OFFSET FLAT:??_C@_05COLMCDPH@Hello?$AA@
	rex_jmp	QWORD PTR [rax+1336]
?NewStringUTF@JNIEnv_@@QEAAPEAV_jstring@@PEBD@Z ENDP	; JNIEnv_::NewStringUTF
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT Java_com_LilG_Com_FozruciX_jniTest
_TEXT	SEGMENT
env$ = 8
__formal$ = 16
Java_com_LilG_Com_FozruciX_jniTest PROC			; COMDAT
; File c:\users\fozrucix\workspace\fozrucix\jni\jnithing\jnithing\jnithing.cpp
; File c:\program files\java\jdk1.8.0_51\include\jni.h
; Line 1611
	mov	rax, QWORD PTR [rcx]
	lea	rdx, OFFSET FLAT:??_C@_05COLMCDPH@Hello?$AA@
	rex_jmp	QWORD PTR [rax+1336]
Java_com_LilG_Com_FozruciX_jniTest ENDP
_TEXT	ENDS
END
