/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LilG_Com_FozruciX_JavaScript */

#ifndef _Included_com_LilG_Com_FozruciX_JavaScript
#define _Included_com_LilG_Com_FozruciX_JavaScript
#ifdef __cplusplus
extern "C" {
#endif
#undef com_LilG_Com_FozruciX_JavaScript_MIN_PRIORITY
#define com_LilG_Com_FozruciX_JavaScript_MIN_PRIORITY 1L
#undef com_LilG_Com_FozruciX_JavaScript_NORM_PRIORITY
#define com_LilG_Com_FozruciX_JavaScript_NORM_PRIORITY 5L
#undef com_LilG_Com_FozruciX_JavaScript_MAX_PRIORITY
#define com_LilG_Com_FozruciX_JavaScript_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
