/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LilG_Com_FozruciX */

#ifndef _Included_com_LilG_Com_FozruciX
#define _Included_com_LilG_Com_FozruciX
#ifdef __cplusplus
extern "C" {
#endif
#undef com_LilG_Com_FozruciX_VERSION
#define com_LilG_Com_FozruciX_VERSION 2.2
#undef com_LilG_Com_FozruciX_JOKE_COMMANDS
#define com_LilG_Com_FozruciX_JOKE_COMMANDS 0L
#undef com_LilG_Com_FozruciX_ARRAY_OFFSET_SET
#define com_LilG_Com_FozruciX_ARRAY_OFFSET_SET 1L
#undef com_LilG_Com_FozruciX_CLEVER_BOT_INT
#define com_LilG_Com_FozruciX_CLEVER_BOT_INT 2L
#undef com_LilG_Com_FozruciX_PANDORA_BOT_INT
#define com_LilG_Com_FozruciX_PANDORA_BOT_INT 3L
#undef com_LilG_Com_FozruciX_JABBER_BOT_INT
#define com_LilG_Com_FozruciX_JABBER_BOT_INT 4L
#undef com_LilG_Com_FozruciX_NICK_IN_USE
#define com_LilG_Com_FozruciX_NICK_IN_USE 5L
#undef com_LilG_Com_FozruciX_COLOR
#define com_LilG_Com_FozruciX_COLOR 6L
#undef com_LilG_Com_FozruciX_RESPOND_TO_PMS
#define com_LilG_Com_FozruciX_RESPOND_TO_PMS 7L
#undef com_LilG_Com_FozruciX_DATA_LOADED
#define com_LilG_Com_FozruciX_DATA_LOADED 8L
#undef com_LilG_Com_FozruciX_CHECK_LINKS
#define com_LilG_Com_FozruciX_CHECK_LINKS 9L
/*
 * Class:     com_LilG_Com_FozruciX
 * Method:    jniTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_LilG_Com_FozruciX_jniTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
