/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LilG_Com_FozruciX_Python */

#ifndef _Included_com_LilG_Com_FozruciX_Python
#define _Included_com_LilG_Com_FozruciX_Python
#ifdef __cplusplus
extern "C" {
#endif
#undef com_LilG_Com_FozruciX_Python_MIN_PRIORITY
#define com_LilG_Com_FozruciX_Python_MIN_PRIORITY 1L
#undef com_LilG_Com_FozruciX_Python_NORM_PRIORITY
#define com_LilG_Com_FozruciX_Python_NORM_PRIORITY 5L
#undef com_LilG_Com_FozruciX_Python_MAX_PRIORITY
#define com_LilG_Com_FozruciX_Python_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
