/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LilG_Com_m68k_M68kSimImpl */

#ifndef _Included_com_LilG_Com_m68k_M68kSimImpl
#define _Included_com_LilG_Com_m68k_M68kSimImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_LilG_Com_m68k_M68kSimImpl
 * Method:    adda
 * Signature: (Lcom/LilG/Com/m68k/M68kSim/Size;JI)V
 */
JNIEXPORT void JNICALL Java_com_LilG_Com_m68k_M68kSimImpl_adda
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     com_LilG_Com_m68k_M68kSimImpl
 * Method:    move
 * Signature: (Lcom/LilG/Com/m68k/M68kSim/Size;JI)V
 */
JNIEXPORT void JNICALL Java_com_LilG_Com_m68k_M68kSimImpl_move
  (JNIEnv *, jobject, jobject, jlong, jint);

/*
 * Class:     com_LilG_Com_m68k_M68kSimImpl
 * Method:    getByte
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_LilG_Com_m68k_M68kSimImpl_getByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_LilG_Com_m68k_M68kSimImpl
 * Method:    getWord
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_LilG_Com_m68k_M68kSimImpl_getWord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_LilG_Com_m68k_M68kSimImpl
 * Method:    getLongWord
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_LilG_Com_m68k_M68kSimImpl_getLongWord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_LilG_Com_m68k_M68kSimImpl
 * Method:    clearMem0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_LilG_Com_m68k_M68kSimImpl_clearMem0
  (JNIEnv *, jobject);

/*
 * Class:     com_LilG_Com_m68k_M68kSimImpl
 * Method:    getRamStart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_LilG_Com_m68k_M68kSimImpl_getRamStart
  (JNIEnv *, jobject);

/*
 * Class:     com_LilG_Com_m68k_M68kSimImpl
 * Method:    getRamSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_LilG_Com_m68k_M68kSimImpl_getRamSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
