/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LilG_Com_FozruciX_EventType */

#ifndef _Included_com_LilG_Com_FozruciX_EventType
#define _Included_com_LilG_Com_FozruciX_EventType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
