/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_LilG_Com_FozruciX_Network */

#ifndef _Included_com_LilG_Com_FozruciX_Network
#define _Included_com_LilG_Com_FozruciX_Network
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
