//
// Created by ggonz on 3/10/2017.
//

#ifndef M68KSIMULATOR_CHKINSTRUCTIONEXCEPTION_H
#define M68KSIMULATOR_CHKINSTRUCTIONEXCEPTION_H


class CHKInstructionException {

};


#endif //M68KSIMULATOR_CHKINSTRUCTIONEXCEPTION_H
