//
// Created by ggonz on 3/10/2017.
//

#ifndef M68KSIMULATOR_ILLEGALINSTRUCTIONEXCEPTION_H
#define M68KSIMULATOR_ILLEGALINSTRUCTIONEXCEPTION_H


class IllegalInstructionException {

};


#endif //M68KSIMULATOR_ILLEGALINSTRUCTIONEXCEPTION_H
