//
// Created by ggonz on 3/10/2017.
//

#ifndef M68KSIMULATOR_PRIVILEGEVIOLATIONEXCEPTION_H
#define M68KSIMULATOR_PRIVILEGEVIOLATIONEXCEPTION_H


class PrivilegeViolationException {

};


#endif //M68KSIMULATOR_PRIVILEGEVIOLATIONEXCEPTION_H
