//
// Created by ggonz on 3/10/2017.
//

#ifndef M68KSIMULATOR_ZERODIVIDEEXCEPTION_H
#define M68KSIMULATOR_ZERODIVIDEEXCEPTION_H


class ZeroDivideException {

};


#endif //M68KSIMULATOR_ZERODIVIDEEXCEPTION_H
